version: '3'
volumes:
    dados:
networks:
    banco:
    web:
    fila:
services: 
    db:
        image: 'postgres:14'
        ports:
            - '5432:5432'
        environment:
            PGPASSWORD: 'password-secret'
            POSTGRES_DB: 'postgres'
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'password-secret'
        volumes:
            #Volume dos dados
            - '/var/lib/postgresql/data'
            #Scripts
            - ./scripts:/scripts
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - banco
    frontend:
        image: nginx:1.13
        volumes:
            #Site
            - ./web:/usr/share/nginx/html/
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        networks:
            - web
        depends_on:
            - app
    app:
        image: python:3.6
        volumes:
            #Aplicação
            - ./app:/app
        working_dir: /app
        command: bash ./app.sh
        ports:
            - 8080:8080
        networks:
            - banco
            - web
            - fila
        depends_on:
            - db       
            - queue
        environment:
            - DB_NAME=email_sender
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
            retries: 3
            timeout: 5s
    queue:
        image: redis:3.2
        networks:
            - fila    
    worker:
        build: worker
        volumes:
            #Worker
            - ./worker:/worker
        working_dir: /worker
        command: worker.py
        networks: 
            - fila
        depends_on:
            - queue

